### ISSUE TITLE
TypeError: Wysiwyg is not a constructor

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#135]
On Odoo 14 when you install website module, we get this error:

Traceback:
TypeError: Wysiwyg is not a constructor
    at http://localhost:14069/web/content/663-edd9a5e/1/web.assets_common_lazy.js:5100:55
    at async Class._startEditMode (http://localhost:14069/web/content/665-b61c0b5/1/website.assets_editor.js:56:26)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 2)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)

And every time you want to edit a Page:

Traceback:
TypeError: Wysiwyg is not a constructor
    at http://localhost:14069/web/content/663-edd9a5e/1/web.assets_common_lazy.js:5100:55
    at async Class._startEditMode (http://localhost:14069/web/content/904-9b9fe7f/1/website.assets_editor.js:56:26)
    at async Promise.all (index 0)

**Comment by carlosecv** [comment]
It worked erasing Navigation History and cookies
