### ISSUE TITLE
common/entrypoint 'No such file or directory' error

### ISSUE THREAD

**Issue by ahmed3991** [Tecnativa/doodba-copier-template#138]
I have this error when I call ```docker-compose up```, 
```doodba INFO: Executing odoo --limit-memory-soft=0 --limit-time-real-cron=9999999 --limit-time-real=9999999 --workers=0 --dev=reload,qweb,werkzeug,xml
odoo_1                    | Traceback (most recent call last):
odoo_1                    |   File "/opt/odoo/common/entrypoint", line 75, in <module>
odoo_1                    |     os.execvp(extra_command[0], extra_command)
odoo_1                    |   File "/usr/local/lib/python3.6/os.py", line 559, in execvp
odoo_1                    |     _execvpe(file, args)
odoo_1                    |   File "/usr/local/lib/python3.6/os.py", line 604, in _execvpe
odoo_1                    |     raise last_exc.with_traceback(tb)
odoo_1                    |   File "/usr/local/lib/python3.6/os.py", line 594, in _execvpe
odoo_1                    |     exec_func(fullname, *argrest)
odoo_1                    | FileNotFoundError: [Errno 2] No such file or directory```

**Comment by patovala** [comment]
I have the same issue, seems like `odoo` as a command is not available, perhaps I forgot to include the image in the build or I miss some step?

**Comment by patovala** [comment]
I solved it running the `invoke git-aggregate` command, probably I missed that one from the documentation.

**Comment by joao-p-marques** [comment]
Thanks for the response @patovala 

Indeed, that is a necessary command (for reference, see https://github.com/Tecnativa/doodba-copier-template/blob/stable/docs/daily-usage.md#development)

Closing this as it seems to be fixed. Feel free to reopen if your problem is not fixed.
