### ISSUE TITLE
vanilla traefik 2 sample

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#196]
Yajo

Do you have an sample for traekik 2 proxy to get working website edition for odoo 14?

Im having issues trying to get it working with traefik version 1 sample that is on docs, in traefik saple version 1 it worked with previous odoo versions not now.

Regards

**Comment by carlosecv** [comment]
Traceback:
TypeError: Cannot read property 'getRange' of undefined
    at https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:5112:762
    at Function._.each._.forEach (https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:9:558)
    at https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:5112:662
    at async Class._startEditMode (https:/mydomain.com.mx/web/content/216-dde5719/1/website.assets_editor.js:56:26)
    at async Promise.all (index 0)

**Comment by carlosecv** [comment]
This trows logs:

 2020-12-10 03:16:41,225 11158 INFO ? odoo: Odoo version 14.0 
odoo_1                        | 2020-12-10 03:16:41,225 11158 INFO ? odoo: Using configuration file at /opt/odoo/auto/odoo.conf 
odoo_1                        | 2020-12-10 03:16:41,225 11158 INFO ? odoo: addons paths: ['/opt/odoo/custom/src/odoo/odoo/addons', '/var/lib/odoo/addons/14.0', '/opt/odoo/auto/addons'] 
odoo_1                        | 2020-12-10 03:16:41,225 11158 INFO ? odoo: database: odoo14@db:5432 
odoo_1                        | 2020-12-10 03:16:41,442 11158 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
odoo_1                        | <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject

**Comment by carlosecv** [comment]
Well I solved part of the issue that appears on log:
odoo_1 | :219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject

add to odoo/custom/dependencies/pip.txt 
gevent==20.9.0

thanks to:

https://github.com/python-greenlet/greenlet/issues/178#issuecomment-697342964

**Comment by Yajo** [comment]
> Do you have an sample for traekik 2 proxy to get working website edition for odoo 14?

Not for now. Traefik 2 is very much more configurable than traefik 1, so it's not as easy to provide a working setup that works for everybody.

I'll leave this open, though, labeled with *help wanted*, so anybody from the community can contribute such thing to the docs and we'll review it.

**Comment by carlosecv** [comment]
I know that this is not a plug and play issue.

If someone has been successful in using copier template with odoo 14 in a productive way, with a Traefik 2 or Traefik 1 proxy, please share your basic configuration, both of your Trarefik proxy, and labels that allow you to edit your web portal.

Regards,

**Comment by gdgellatly** [comment]
maybe my comments in #116 help

**Comment by luismata01** [comment]
> ```
> Traceback:
> TypeError: Cannot read property 'getRange' of undefined
>     at https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:5112:762
>     at Function._.each._.forEach (https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:9:558)
>     at https://mydomain.com.mx/web/content/214-260d0ef/1/web.assets_common_lazy.js:5112:662
>     at async Class._startEditMode (https:/mydomain.com.mx/web/content/216-dde5719/1/website.assets_editor.js:56:26)
>     at async Promise.all (index 0)
> ```

I have the same error, any update about this solution?

**Comment by rquevedo** [comment]
To fix this and as a quick fix, run 'copier update' and set parameter 'paths_without_crawlers' to empty [] and update your build 'docker-compose up -d'. After odoo stop to show js error, you can set defaults values for this parameter again.

**Comment by pedrobaeza** [comment]
Check #469
