### ISSUE TITLE
Can't user env variable in repos.yaml

### ISSUE THREAD

**Issue by obayit** [Tecnativa/doodba-copier-template#211]
I have the following repo:
```
./odoo-staging:
  defaults:
    depth: $DEPTH_MERGE
  remotes:
    main: git@github.com:obayit/project.git
  target: main project
  merges:
    - main project
    - main refs/pull/$TEST_PR/head
```
When I run `docker-compose -f test.yaml build` I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/gitaggregate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/main.py", line 176, in main
    run(args)
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/main.py", line 237, in run
    args.config, args.expand_env, args.env_file, args.force)
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/config.py", line 159, in load_config
    config = config.substitute(environment)
  File "/usr/local/lib/python3.5/string.py", line 129, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/local/lib/python3.5/string.py", line 119, in convert
    val = mapping[named]
KeyError: 'TEST_PR'
```
The variable is defined with `export TEST_PR=246`, also tried adding it to `.docker/odoo.env` with no luck.

**Comment by obayit** [comment]
Never mind, this is more of a docker issue.
I just found out that at build time the environment variables should be provided in the Dockerfile itself, or in the compose file in the `build.args`
