### ISSUE TITLE
ERROR ? odoo.modules.loading: Database devel not initialized, you can force it with `-i base` 

### ISSUE THREAD

**Issue by anderwm** [Tecnativa/doodba-copier-template#27]
I get this error in the devel environment when using more or less stock answers from the copier-template. It seems to be related to https://github.com/odoo/odoo/issues/27447. 

If I try to run:

```
docker-compose exec odoo bash
odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo
```

I get:

```
2020-04-06 21:30:14,274 60 INFO ? odoo: Odoo version 13.0 
2020-04-06 21:30:14,274 60 INFO ? odoo: Using configuration file at /opt/odoo/auto/odoo.conf 
2020-04-06 21:30:14,275 60 INFO ? odoo: addons paths: ['/opt/odoo/custom/src/odoo/odoo/addons', '/var/lib/odoo/addons/13.0', '/opt/odoo/auto/addons'] 
2020-04-06 21:30:14,275 60 INFO ? odoo: database: odoo@db:5432 
2020-04-06 21:30:14,277 60 INFO ? odoo.sql_db: Connection to the database failed 
Traceback (most recent call last):
  File "/usr/local/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/opt/odoo/custom/src/odoo/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 178, in run
    main(args)
  File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 142, in main
    odoo.service.db._create_empty_database(db_name)
  File "/opt/odoo/custom/src/odoo/odoo/service/db.py", line 98, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 650, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 187, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 533, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 601, in borrow
    **connection_info)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "odoo"
```

It is possible that I am misunderstanding how the password gets set in devel, the documentation isn't as clear with copier-template as from the old scaffolding and I'm a first time user. Is this a bug or a mistake on my part?

**Comment by Yajo** [comment]
Sorry, I still didn't have time to update the docs. This is odoo's bug, not ours. Just run this the 1st time you boot a project:

```bash
docker-compose run --rm odoo --stop-after-init -i base
```

**Comment by anderwm** [comment]
Thanks, this worked

**Comment by Ableson** [comment]
启动odoo需要初始化数据库， 可以通过增加启动配置 -i base 即可 例如:-c odoo.conf -i base

**Comment by BruckFikre** [comment]
just db_name= 'ecom'              

put in ''

**Comment by MarinosTBH** [comment]
> in odoo.conf db_name= 'ecom'
> 
> put in ''

Really, this is an odoo's problem right ?
