### ISSUE TITLE
ModuleNotFoundError: No module named 'openerp'

### ISSUE THREAD

**Issue by patovala** [Tecnativa/doodba-copier-template#273]
No module named 'odoo' while running `invoke resetdb`

## Describe the bug

```
pre-commit installed at .git/hooks/pre-commit
Creating pbox-odoo14_odoo_run ... done
doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
doodba INFO: Executing click-odoo-dropdb devel
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/click_odoo/env.py", line 8, in <module>
    import odoo
ModuleNotFoundError: No module named 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/click-odoo-dropdb", line 5, in <module>
    from click_odoo_contrib.dropdb import main
  File "/usr/local/lib/python3.8/site-packages/click_odoo_contrib/dropdb.py", line 9, in <module>
    import click_odoo
  File "/usr/local/lib/python3.8/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env import OdooEnvironment  # noqa
  File "/usr/local/lib/python3.8/site-packages/click_odoo/env.py", line 17, in <module>
    import openerp as odoo
ModuleNotFoundError: No module named 'openerp'
```

## To Reproduce

**Affected versions**:

1. using odoo 14 after doing 
2. `invoke resetdb`

no reset db and no database created

Using: 
debian: Debian GNU/Linux 10 (buster)
docker: Docker version 20.10.8, build 3967b7d

**Comment by pedrobaeza** [comment]
No further answers, so closing.
