### ISSUE TITLE
pre-commit: black < 22.3.0 is incompatible with click 8.1.0

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba-copier-template#327]
## Describe the bug

Running copier in a project copied from doodba-copier-template because of https://github.com/psf/black/issues/2964 we get the following error:
```
 File "/home/copier/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 297, in main
    dst_path=destination_path, only_diff=self.only_diff,
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 187, in _copy
    **kwargs,
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 145, in copy
    update_diff(conf=conf)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 264, in update_diff
    git("commit", "--allow-empty", "-am", "dumb commit 2")
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/commands/base.py", line 99, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/commands/processes.py", line 322, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/commands/processes.py", line 24, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/copier/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/machines/base.py", line 29, in verify
    getattr(self, "argv", None), self.returncode, stdout, stderr
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/bin/git commit --allow-empty -am 'dumb commit 2'
Stderr:       | forbidden files......................................(no files to check)Skipped
              | Update pre-commit excluded addons........................................Passed
              | autoflake................................................................Passed
              | black....................................................................Failed
              | - hook id: black
              | - exit code: 1
              | 
              | Traceback (most recent call last):
              |   File "/home/copier/.cache/pre-commit/repowck2sql2/py_env-python3/bin/black", line 8, in <module>
              |     sys.exit(patched_main())
              |   File "/home/copier/.cache/pre-commit/repowck2sql2/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6606, in patched_main
              |     patch_click()
              |   File "/home/copier/.cache/pre-commit/repowck2sql2/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6595, in patch_click
              |     from click import _unicodefun  # type: ignore
              | ImportError: cannot import name '_unicodefun' from 'click' (/home/copier/.cache/pre-commit/repowck2sql2/py_env-python3/lib/python3.7/site-packages/click/__init__.py)
              | 
              | pyupgrade................................................................Passed
              | isort except __init__.py.................................................Passed
              | prettier + plugin-xml....................................................Passed
              | Trim Trailing Whitespace.................................................Passed
              | Fix End of Files.........................................................Passed
              | Debug Statements (Python)................................................Passed
              | Fix python encoding pragma...............................................Passed
              | Check for case conflicts.................................................Passed
              | Check docstring is first.................................................Passed
              | Check that executables have shebangs.................(no files to check)Skipped
              | Check for merge conflicts................................................Passed
              | Check for broken symlinks............................(no files to check)Skipped
              | Check Xml............................................(no files to check)Skipped
              | Mixed line ending........................................................Passed
              | flake8 except __init__.py................................................Passed
              | flake8 only __init__.py..............................(no files to check)Skipped
              | pylint with optional checks..............................................Passed
              | - hook id: pylint
              | - duration: 2.5s
              | pylint with mandatory checks.............................................Passed
              | eslint...............................................(no files to check)Skipped
              | - hook id: eslint
```

## To Reproduce

**Affected versions**:

1. run copier in a project copied from doodba-copier-template

**Expected behavior**
No errors/exceptions are shown if the code in the project is ok.

**Additional context** 
See https://github.com/psf/black/issues/2964

Either upgrade black in .pre-commit-config.yaml and .pre-commit-config.yaml.jinja or pin click to < 8.1.0:
```yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
```
```yaml
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        additional_dependencies: ["click<8.1.0"]
```

**Comment by ap-wtioit** [comment]
@Tardo thanks for the prompt fix
