### ISSUE TITLE
Unable to render the required templates for the assets to load: XmlHttpRequestError 

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#353]
## Describe the bug

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://odoo16.realsystems.com.mx/web/assets/293-5ee1e35/web.assets_common.min.js:1212:101)
    at owl.App.handleError (https://odoo16.realsystems.com.mx/web/assets/293-5ee1e35/web.assets_common.min.js:2039:29)
    at ComponentNode.initiateRender (https://odoo16.realsystems.com.mx/web/assets/293-5ee1e35/web.assets_common.min.js:1520:19)

Caused by: Unable to render the required templates for the assets to load: XmlHttpRequestError 

## To Reproduce
On productive environment Select User Prefernces and get this error.

**Affected versions**:
Odoo 16

1. Install via copier odoo 16
2. Go to User on right top corner and select preferences
3. Get error only on productive environment this is not happending on dev environment

**Expected behavior** A clear and concise description of what you expected to happen.

Must show Preferences as on dev environment

**Additional context** Add any other context about the problem here. (e.g. OS, Docker
version, ...)

**Comment by carlosecv** [comment]
Found again a solution you must comment this lines on prod.yaml


#      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
#      "X-Robots-Tag:noindex, nofollow"
#      traefik.forbiddenCrawlers-0.frontend.rule: Host:your.domain.name;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
