### ISSUE TITLE
Getting packaging.version.InvalidVersion: Invalid version: 'v0.0.0-0-0' on copier copy ...

### ISSUE THREAD

**Issue by kevin-fritsch** [Tecnativa/doodba-copier-template#361]
## Describe the bug

System information `lsb_release -a`:

> Distributor ID: Debian
> Description:    Debian GNU/Linux 11 (bullseye)
> Release:        11
> Codename:       bullseye

On command
```bash
copier copy gh:Tecnativa/doodba-copier-template ~/odoo
```
I get the following traceback
```
Traceback (most recent call last):
  File "/home/pi/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/pi/.local/lib/python3.9/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/pi/.local/lib/python3.9/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/cli.py", line 294, in main
    self.parent._worker(
  File "/home/pi/.local/lib/python3.9/site-packages/copier/main.py", line 620, in run_copy
    src_abspath = self.template_copy_root
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/main.py", line 593, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/template.py", line 402, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/template.py", line 263, in config_data
    result = filter_config(self._raw_config)[0]
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/template.py", line 222, in _raw_config
    for p in self.local_abspath.glob("copier.*")
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/template.py", line 439, in local_abspath
    checkout_latest_tag(result, self.use_prereleases)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/vcs.py", line 109, in checkout_latest_tag
    sorted_tags = sorted(all_tags, key=version.parse, reverse=True)
  File "/home/pi/.local/lib/python3.9/site-packages/copier/vcs.py", line 107, in <lambda>
    lambda tag: not version.parse(tag).is_prerelease, all_tags
  File "/home/pi/.local/lib/python3.9/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/pi/.local/lib/python3.9/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v0.0.0-0-0'
```

## To Reproduce

**Affected versions**:

v5.1.0

1. Install the following pipx packages
```bash
python3 -m pip install --user pipx
pipx install docker-compose
pipx install copier
pipx install invoke
pipx install pre-commit
pipx ensurepath
```
2. Add a odoo directory in the home directory 
```bash
mkdir ~/odoo
```
3. Try to execute the command
```bash
copier copy gh:Tecnativa/doodba-copier-template ~/odoo
```

Error occurs...

**Expected behavior** 

Copier should not raise this error.

**Comment by eblandon** [comment]
I have the same error with:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
----------------
and:

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
-----------------

**Comment by kevin-fritsch** [comment]
@eblandon I found a fix for me.

```bash
copier copy gh:kevin-fritsch/doodba-copier-template ~/odoo
```

The version key in this line caused the problem:
https://github.com/tecnativa/doodba-copier-template/blob/main/copier.yml#L48
https://github.com/kevin-fritsch/doodba-copier-template/blob/main/copier.yml#L48

**Comment by syci** [comment]
@eblandon With this command you have no problem:

`copier -r v5.1.1 copy gh:Tecnativa/doodba-copier-template ~/odoo`
