### ISSUE TITLE
invoke resetdb: subprocess.CalledProcessError: Command '/opt/odoo/common/entrypoint.d/40-addons-link'

### ISSUE THREAD

**Issue by crsilveira** [Tecnativa/doodba-copier-template#363]
Hi thank you for your project!

I had an issue when run odoo 12:

doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Unaccent extension installed
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
Traceback (most recent call last):
  File "/opt/odoo/common/entrypoint.d/40-addons-link", line 14, in <module>
    for addon, repo in addons_config():
  File "/usr/local/lib/python3.5/site-packages/doodbalib/__init__.py", line 106, in addons_config
    all_globs[repo].update(partial_globs)
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/opt/odoo/common/entrypoint", line 30, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/common/entrypoint.d/40-addons-link' returned non-zero exit status 1
ERROR: 1

**Comment by chienandalu** [comment]
Hi @crsilveira 

Looks like your addons.yaml has some kind of error

**Comment by chienandalu** [comment]
This would be valid anyway:

```yaml
account-payment: ["*"]
```
