### ISSUE TITLE
[v14CE] copier copy error when try to run 'copier copy gh:Tecnativa/doodba-copier-template'

### ISSUE THREAD

**Issue by devkami** [Tecnativa/doodba-copier-template#367]
## Invalid Version Error 
When i try to run 'copier copy gh:Tecnativa/doodba-copier-template';
The error message below appear:
Traceback (most recent call last):
  File "/home/maicondmenezes/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 294, in main
    self.parent._worker(
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 620, in run_copy
    src_abspath = self.template_copy_root
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 593, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/template.py", line 402, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/template.py", line 263, in config_data
    result = filter_config(self._raw_config)[0]
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/template.py", line 222, in _raw_config
    for p in self.local_abspath.glob("copier.*")
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/template.py", line 439, in local_abspath
    checkout_latest_tag(result, self.use_prereleases)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/vcs.py", line 109, in checkout_latest_tag
    sorted_tags = sorted(all_tags, key=version.parse, reverse=True)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/vcs.py", line 107, in <lambda>
    lambda tag: not version.parse(tag).is_prerelease, all_tags
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/maicondmenezes/.local/pipx/venvs/copier/lib/python3.9/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v0.0.0-0-0'

## To Reproduce
Just install the requirements and try to copy the template

**Affected versions**:

1.Install dependences:
https://github.com/Tecnativa/doodba-copier-template#install-the-dependencies

2. Install requirements:
python3 -m pip install --user pipx
pipx install docker-compose
pipx install copier
pipx install invoke
pipx install pre-commit
pipx ensurepath

3. Run copier template command:
copier copy gh:Tecnativa/doodba-copier-template

**Expected behavior** A clear and concise description of what you expected to happen.
Start's template copier wizard

**Comment by pedrobaeza** [comment]
This was fixed in #364 

Have you checked again recently?

**Comment by devkami** [comment]
thanks i will check,
Do you have a full course about infrastructure and/or devops operations
with odoo and tecnativa template?

**Comment by eccit-quim** [comment]
I have exactly the same error now.
It's strange, #364 seems like it should have solved it but it doesn't.

Ubuntu 22.04

```
$ copier copy gh:Tecnativa/doodba-copier-template ~/Dev/doodba-test
Traceback (most recent call last):
  File "/home/quim/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 298, in main
    ).run_copy()
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 620, in run_copy
    src_abspath = self.template_copy_root
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 593, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 402, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 263, in config_data
    result = filter_config(self._raw_config)[0]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 222, in _raw_config
    for p in self.local_abspath.glob("copier.*")
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 439, in local_abspath
    checkout_latest_tag(result, self.use_prereleases)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/vcs.py", line 109, in checkout_latest_tag
    sorted_tags = sorted(all_tags, key=version.parse, reverse=True)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/vcs.py", line 107, in <lambda>
    lambda tag: not version.parse(tag).is_prerelease, all_tags
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/quim/.local/pipx/venvs/copier/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v0.0.0-0-0'
```

**Comment by pedrobaeza** [comment]
Does this happen for new scaffoldings or are you running it in an old one? Which version of copier do you have?

**Comment by eccit-quim** [comment]
Just reinstalled ubuntu 22, and doodba with his requirements today and creating my first doodba test to try it. 

Versions: 
$ copier --version
**copier 7.0.1**
$ pre-commit --version
pre-commit 3.0.1
$ python3 --version
Python 3.10.6

**Comment by pedrobaeza** [comment]
And do you still have the same problem?

**Comment by eccit-quim** [comment]
Yes

El ds., 28 de gen. 2023, 9:13, Pedro M. Baeza ***@***.***> va
escriure:

**Comment by SapphireHotS** [comment]
It still happens.
Using clean debian10 installation, same process:
python3 -m pip install --user pipx
pipx install docker-compose
pipx install copier
pipx install invoke
pipx install pre-commit
pipx ensurepath
copier copy gh:Tecnativa/doodba-copier-template .

**Comment by SapphireHotS** [comment]
Changing LATEST_VERSION_WITHOUT_COPIER = "v0.0.0" yo v0.0.1 works for me in my fork.

**Comment by yajo** [comment]
Copier will keep using the latest released version, and the fix is not yet released.

You can use `copier -r HEAD copy gh:Tecnativa/doodba-copier-template .` in the mean time.

**Comment by pedrobaeza** [comment]
Ouch, I didn't remember about the releasing. Done.
