### ISSUE TITLE
Error when doing invoke git-aggregate on MacOS

### ISSUE THREAD

**Issue by ernesto-garcia-tecnativa** [Tecnativa/doodba-copier-template#371]
## Describe the bug

```
fatal: detected dubious ownership in repository at '/opt/odoo/custom/src/odoo'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/odoo/custom/src/odoo
error: remote did not send all necessary objects
fatal: detected dubious ownership in repository at '/opt/odoo/custom/src/odoo'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/odoo/custom/src/odoo
(ERROR) [15:08:28] git_aggregator.repo  odoo   /opt/odoo/custom/src/odoo> error calling ('git', 'fetch', '--depth', '100', 'ocb', '15.0')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/git_aggregator/main.py", line 219, in aggregate_repo
    repo.aggregate()
  File "/usr/local/lib/python3.8/site-packages/git_aggregator/repo.py", line 183, in aggregate
    self.fetch()
  File "/usr/local/lib/python3.8/site-packages/git_aggregator/repo.py", line 206, in fetch
    self.log_call(cmd, cwd=self.cwd)
  File "/usr/local/lib/python3.8/site-packages/git_aggregator/repo.py", line 160, in log_call
    ret = callwith(cmd, **kw)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('git', 'fetch', '--depth', '100', 'ocb', '15.0')' returned non-zero exit status 1.
```

## To Reproduce
Execute `invoke git-aggregate`

I have been able to solve it putting this line in the devel.yaml

```
service:
  odoo:
    ...
    volumes:
      ...
      - "~/.gitconfig:/etc/gitconfig"
```

**Comment by bosd** [comment]
I'm facing this as well on fedora. 
Resolved it with using `copier recopy --trust`
