### ISSUE TITLE
Old builds failing due to PostgreSQL packages signature key being expired

### ISSUE THREAD

**Issue by yajo** [Tecnativa/doodba-copier-template#374]
You can see [this build failure](https://github.com/Tecnativa/doodba-copier-template/actions/runs/4384238633/jobs/7675468908#step:13:396). I downloaded the logs to make them survive when GC runs: [logs_2284.zip](https://github.com/Tecnativa/doodba-copier-template/files/10954650/logs_2284.zip)

The important part is:

```
Err https://apt-archive.postgresql.org/ jessie-pgdg-archive/main Sources
  HttpError403
Fetched 11.4 MB in 10s (1125 kB/s)
W: GPG error: http://deb.debian.org/ jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673
W: Failed to fetch https://apt-archive.postgresql.org/pub/repos/apt/dists/jessie-pgdg-archive/main/source/Sources  HttpError403

E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 30, in <module>
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/custom/build.d/20-update-pg-repos' returned non-zero exit status 100
```

IIUC the postgresql repos fail to fetch the binaries because the signing key is expired. This is the Odoo 9.0 build, so we can somehow expect this will happen at some point with every other version as they keep getting old.

Ideas for fixes:
- Disable these old version tests. However, if you have to migrate an old v9 some time, you'll get the same problem anyway.
- Rebase on a newer Debian. This could break something, although usually not much. Probable problem: python2.
- Pre-bundle postgresql client binaries. As long as you do the important operations such as backup and restore using the duplicity image, or as long as you keep the postgresql server at a fixed version when deploying v9 instances, thanks to https://github.com/Tecnativa/docker-duplicity/pull/476 this shouldn't be a huge problem.
- Install postgresql in a fashion that will survive the pass of time, such as installing from nixpkgs, building from source or installing from upstream tarballs.

**Comment by yajo** [comment]
Builds today started working, so maybe the Postgres people fixed this.
