### ISSUE TITLE
ERROR Executing Copier

### ISSUE THREAD

**Issue by LingerANR** [Tecnativa/doodba-copier-template#377]
I have an error when executing copier copy gh:Tecnativa/doodba-copier-template, in Kali LInux. It happens that it throws me the following error:

<pre><code><div class="footer">
    Traceback (most recent call last):
  File "/home/linger/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
             ^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/cli.py", line 298, in main
    ).run_copy()
      ^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/main.py", line 620, in run_copy
    src_abspath = self.template_copy_root
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/main.py", line 593, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/template.py", line 402, in subdirectory
    return self.config_data.get("subdirectory", "")
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/template.py", line 263, in config_data
    result = filter_config(self._raw_config)[0]
                           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/template.py", line 222, in _raw_config
    for p in self.local_abspath.glob("copier.*")
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/template.py", line 439, in local_abspath
    checkout_latest_tag(result, self.use_prereleases)
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/vcs.py", line 109, in checkout_latest_tag
    sorted_tags = sorted(all_tags, key=version.parse, reverse=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/copier/vcs.py", line 107, in <lambda>
    lambda tag: not version.parse(tag).is_prerelease, all_tags
                    ^^^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/linger/.local/pipx/venvs/copier/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v0.0.0-0-0'
</div>
</code></pre>

I have installed each pipx dependency successfully, but it keeps throwing me the same error.
Thanks in advance for providing any help you see fit.

**Comment by pedrobaeza** [comment]
Check #367
