### ISSUE TITLE
Python 3.11 support (Py-lint pinned too old version)

### ISSUE THREAD

**Issue by bosd** [Tecnativa/doodba-copier-template#405]
## Describe the bug

On a system with python 3.11 the pre-commit hook fails.

While using the latest Scaffolding template.

## To Reproduce

**Affected versions**: Latest scaffolding template with python 3.11

1. Change a file and run `git commit -m "Update Project Template"`
Traceback 
<details>

```

Traceback (most recent call last):
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/reporters/__init__.py", line 26, in <module>
    from pylint import utils
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/utils/__init__.py", line 46, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/nodes/node_classes.py", line 47, in <module>
    from astroid import decorators, mixins, util
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/decorators.py", line 27, in <module>
    import wrapt
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib64/python3.11/site-packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib64/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib64/python3.11/inspect.py)

pylint with mandatory checks.............................................Failed
- hook id: pylint
- exit code: 1

Traceback (most recent call last):
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/reporters/__init__.py", line 26, in <module>
    from pylint import utils
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/utils/__init__.py", line 46, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/nodes/node_classes.py", line 47, in <module>
    from astroid import decorators, mixins, util
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib/python3.11/site-packages/astroid/decorators.py", line 27, in <module>
    import wrapt
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib64/python3.11/site-packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/home/myuser/.cache/pre-commit/reporjo1wbjm/py_env-python3/lib64/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib64/python3.11/inspect.py)

```

</details>
**Expected behavior** 
Being able to commit changes with pre-commit hooks.

## Cause:
**py-lint** is pinned to a fixed version 2.11.1 which does not support python 3.11

https://github.com/Tecnativa/doodba-copier-template/blob/19b5ecbba0b0c5d645ed44b6d3dc8e680c2c2815/.pre-commit-config.yaml.jinja#L118-L119

**Additional context** 
Pylint version [2.17.0](https://github.com/pylint-dev/pylint/releases/tag/v2.17.0) 

> 2.17 is a small release that is the first to support python 3.11 officially
> with the addition of TryStar nodes.

**Pylint-odoo** is fixed to version 5.0.5. (Which is not latest)

https://github.com/Tecnativa/doodba-copier-template/blob/19b5ecbba0b0c5d645ed44b6d3dc8e680c2c2815/.pre-commit-config.yaml.jinja#L130-L138

**Temporary solution**
I was able to version bump pylint-odoo to 8.0.20 (Latest).
Yet pylint-odoo limits versionbump of pylint to 2.15

https://github.com/OCA/pylint-odoo/blob/84513d20ed69e8a1eaeccec5c37ce0f952a48098/requirements.txt#L2-L3

Version 2.15 was working for me on python 3.11

## **Additional questions** 
Is all this pinning of fixed versions necessary?

**Comment by pedrobaeza** [comment]
#401 should serve for that
