### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by estraka** [Tecnativa/doodba-copier-template#45]
I think it is interesting to clarify in the description of smtp_canonical_domains that they should always be used [ ] even if it is only 1 or modify logic because I had an error, not very descriptive when not putting them that it took me time to discover.

domain_prod_alternatives does not use the same logic. Supports 1 domain without [ ]

Exit in terminal:

```
create  devel.yaml
    create  .copier-answers.yml
    create  .eslintrc.yml
    create  README.md
    create  .editorconfig
    create  prod.yaml
    create  test.yaml
    create  .flake8
    create  .gitignore
    create  tasks.py
    create  .pylintrc
    create  LICENSE
    create  setup-devel.yaml
    create  .pylintrc-mandatory
    create  common.yaml
    create  .prettierrc.yml
    create  .pre-commit-config.yaml
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/Users/estraka/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 17, in _wrapper
    return method(*args, **kwargs)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 148, in main
    self.parent._copy(template_src, destination_path)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 111, in _copy
    **kwargs,
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 138, in copy
    copy_local(conf=conf)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 181, in copy_local
    render_file(conf, rel_path, source_path, render, must_skip)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 308, in render_file
    content = render(src_path)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/tools.py", line 143, in __call__
    return tmpl.render(**self.data)
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/estraka/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/private/var/folders/h4/j40yrxks05n6c6fl_9hyfr880000gn/T/copier.vcs.clone.qkunsvxf/.env.jinja", line 33, in top-level template code
TypeError: can only concatenate list (not "str") to list
```

**Comment by Yajo** [comment]
> domain_prod_alternatives does not use the same logic. Supports 1 domain without [ ]

Be careful, that's not true. The fact it doesn't raise an exception doesn't mean it is supported.



> I think it is interesting to clarify in the description of smtp_canonical_domains that they should always be used [ ] even if it is only 1 or modify logic because I had an error, not very descriptive when not putting them that it took me time to discover.

![Captura de pantalla de 2020-05-04 09-24-20](https://user-images.githubusercontent.com/973709/80948053-41db2a00-8de9-11ea-8dab-076354520a37.png)

:thinking: IMHO it's clear enough...
