### ISSUE TITLE
500 Server error; "directory is not writable" After copier update to 8.1.0

### ISSUE THREAD

**Issue by bosd** [Tecnativa/doodba-copier-template#502]
## Describe the bug

After a copier update one is greeted with a 500 internal server error on production.

/var/lib/odoo/sessions: directory is not writable

```


odoo-1    | 2024-10-25 18:52:27,103 1 ERROR ? odoo.http: Exception during request handling. 
odoo-1    | Traceback (most recent call last):
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/tools/config.py", line 759, in session_dir
odoo-1    |     os.makedirs(d, 0o700)
odoo-1    |   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
odoo-1    |     mkdir(name, mode)
odoo-1    | FileExistsError: [Errno 17] File exists: '/var/lib/odoo/sessions'
odoo-1    | 
odoo-1    | During handling of the above exception, another exception occurred:
odoo-1    | 
odoo-1    | Traceback (most recent call last):
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 2199, in __call__
odoo-1    |     request._post_init()
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1390, in _post_init
odoo-1    |     self.session, self.db = self._get_session_and_dbname()
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1395, in _get_session_and_dbname
odoo-1    |     if not sid or not root.session_store.is_valid_key(sid):
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 28, in __get__
odoo-1    |     value = self.fget(obj)
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 2125, in session_store
odoo-1    |     path = odoo.tools.config.session_dir
odoo-1    |   File "/opt/odoo/custom/src/odoo/odoo/tools/config.py", line 763, in session_dir
odoo-1    |     assert os.access(d, os.W_OK), \
odoo-1    | AssertionError: /var/lib/odoo/sessions: directory is not writable


```

## To Reproduce

1.  copier update --force
2. answer all questions
3. try to get into production with `docker compose -f prod.yaml up`
4. See the above error message

**Affected versions**:

Updated from template version 7.0.1 to 8.1.0.

**Expected behavior** 
no error, an up and running odoo :smile: 

**Additional context**
odoo version 17.0
copier 9.2.0
Docker Compose version v2.28.1
Docker version 27.0.3

**Comment by pedrobaeza** [comment]
Can you try in a clean one? It says `[Errno 17] File exists: '/var/lib/odoo/sessions'`

**Comment by bosd** [comment]
Thanks,
I have been able to solve it.
Updated copier and docker.
Started fresh by going to the last working version of my project.
Repeated the steps from the opening post. 

Everything was working as expected.
