### ISSUE TITLE
Trying copier on fresh Debian 10 install

### ISSUE THREAD

**Issue by bosd** [Tecnativa/doodba-copier-template#60]
I've setup a fresh host Debian 10 vps.
Tried multiple fresh installs of Debian 10, but was unable to get an project up and running.
Tried multiple combinations of odoo and postgres versions as well.
Yet, it keeps breaking on file not found error.
What's going wrong here?

<details>
<summary>logs</summary>
copy of odoo log

 ``` 
~/myproject$ sudo docker-compose -f test.yaml up
[sudo] password for user: 

WARNING: The SMTP_REAL_NON_CANONICAL_DEFAULT variable is not set. Defaulting to a blank string.
Starting myproject_db_1   ... done
Starting myproject_smtp_1 ... done
Starting myproject_odoo_1 ... done
Attaching to myproject_smtp_1, myproject_db_1, myproject_odoo_1
db_1    | 
db_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1    | 
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2020-06-08 09:48:42.131 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1    | 2020-06-08 09:48:42.154 GMT [20] LOG:  database system was shut down at 2020-06-08 08:27:08 GMT
db_1    | 2020-06-08 09:48:42.166 GMT [1] LOG:  database system is ready to accept connections
smtp_1  | 2020/06/08 09:48:41 Using in-memory storage
smtp_1  | 2020/06/08 09:48:41 [SMTP] Binding to address: 0.0.0.0:1025
smtp_1  | 2020/06/08 09:48:41 Serving under http://0.0.0.0:8025/
smtp_1  | [HTTP] Binding to address: 0.0.0.0:8025
smtp_1  | Creating API v1 with WebPath: 
smtp_1  | Creating API v2 with WebPath: 
odoo_1  | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1  |   """)
odoo_1  | doodba INFO: Waiting until postgres is listening at db...
odoo_1  | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1  | doodba INFO: File /opt/odoo/auto/odoo.conf exists, skipping config generation
odoo_1  | doodba INFO: Executing odoo --workers=2 --max-cron-threads=1
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/common/entrypoint", line 61, in <module>
odoo_1  |     os.execvp(extra_command[0], extra_command)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 559, in execvp
odoo_1  |     _execvpe(file, args)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 604, in _execvpe
odoo_1  |     raise last_exc.with_traceback(tb)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 594, in _execvpe
odoo_1  |     exec_func(fullname, *argrest)
odoo_1  | FileNotFoundError: [Errno 2] No such file or directory
odoo_1  | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1  |   """)
odoo_1  | doodba INFO: Waiting until postgres is listening at db...
odoo_1  | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1  | doodba INFO: File /opt/odoo/auto/odoo.conf exists, skipping config generation
odoo_1  | doodba INFO: Executing odoo --workers=2 --max-cron-threads=1
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/common/entrypoint", line 61, in <module>
odoo_1  |     os.execvp(extra_command[0], extra_command)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 559, in execvp
odoo_1  |     _execvpe(file, args)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 604, in _execvpe
odoo_1  |     raise last_exc.with_traceback(tb)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 594, in _execvpe
odoo_1  |     exec_func(fullname, *argrest)
odoo_1  | FileNotFoundError: [Errno 2] No such file or directory
myproject_odoo_1 exited with code 1

```
</details>

**Comment by Yajo** [comment]
You're giving me the results but not how you got there. Please share the whole story on how you get from zero to those errors. Do this, from scratch:

```bash
which copier
which invoke
which docker-compose
copier --version
invoke --version
docker-compose version
docker info
copier -f copy gh:Tecnativa/doodba-copier-template subproject
cd subproject
invoke git-aggregate
invoke start
docker-compose logs
```

Then report back all the logs produced by this session.

**Comment by bosd** [comment]
The python version on this system is 3.7.3
(I noticed 3.6.9 is causing issues with pre-commit)

copier=3.2.0
invoke=1.4.1
docker-compose version
```docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 85
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 987.2MiB
 Name: 136-144-218-229
 ID: 4FZR:UVBV:2N2H:6UVQ:QZ5S:XXPX:M3YI:FSGP:2EHZ:JZLY:L2RY:I5SH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
So for clarity I repeated the steps and created a new project named "subproject"
``copier -f copy gh:Tecnativa/doodba-copier-template subproject``
response:
```

    create  .flake8
    create  .isort.cfg
    create  .pylintrc-mandatory
    create  test.yaml
    create  .editorconfig
    create  .eslintrc.yml
    create  README.md
    create  setup-devel.yaml
    create  prod.yaml
    create  LICENSE
    create  .pylintrc
    create  .pre-commit-config.yaml
    create  .env
    create  .prettierrc.yml
    create  devel.yaml
    create  .gitignore
    create  .copier-answers.yml
    create  common.yaml
    create  tasks.py
    create  .vscode/
    create  .vscode/launch.json
    create  .vscode/tasks.json
    create  .vscode/settings.json
    create  .vscode/extensions.json
    create  .vscode/doodba.code-snippets
    create  .docker/
    create  .docker/db-access.env
    create  .docker/db-creation.env
    create  .docker/odoo.env
    create  odoo/
    create  odoo/.dockerignore
    create  odoo/Dockerfile
    create  odoo/custom/
    create  odoo/custom/src/
    create  odoo/custom/src/repos.yaml
    create  odoo/custom/src/addons.yaml
    create  odoo/custom/src/private/
    create  odoo/custom/src/private/.editorconfig
    create  odoo/custom/build.d/
    create  odoo/custom/build.d/.empty
    create  odoo/custom/dependencies/
    create  odoo/custom/dependencies/npm.txt
    create  odoo/custom/dependencies/pip.txt
    create  odoo/custom/dependencies/apt.txt
    create  odoo/custom/dependencies/apt_build.txt
    create  odoo/custom/dependencies/gem.txt
    create  odoo/custom/conf.d/
    create  odoo/custom/conf.d/.empty
    create  odoo/custom/ssh/
    create  odoo/custom/ssh/id_rsa.pub
    create  odoo/custom/ssh/config
    create  odoo/custom/ssh/id_rsa
    create  odoo/custom/ssh/known_hosts
    create  odoo/custom/entrypoint.d/
    create  odoo/custom/entrypoint.d/.empty

 > Running task 1 of 1: invoke develop
Initialized empty Git repository in /home/int/subproject/.git/
```
then
``cd subproject``
run the command
``invoke git-aggregate``
returns
```
Reinitialized existing Git repository in /home/int/subproject/.git/
pre-commit installed at .git/hooks/pre-commit
Creating network "subproject_public" with the default driver
Building odoo
Step 1/2 : ARG ODOO_VERSION
Step 2/2 : FROM tecnativa/doodba:${ODOO_VERSION}-onbuild
# Executing 38 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> b86271c3a23c

[Warning] One or more build-args [PYTHONOPTIMIZE] were not consumed
Successfully built b86271c3a23c
Successfully tagged subproject_odoo:latest
Image for service odoo was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
doodba INFO: Running gitaggregate with /opt/odoo/custom/src/repos.yaml
(INFO) [10:22:16] git_aggregator.repo  odoo   Start aggregation of /opt/odoo/custom/src/odoo
(INFO) [10:22:16] git_aggregator.repo  odoo   Init empty git repository in /opt/odoo/custom/src/odoo
Initialized empty Git repository in /opt/odoo/custom/src/odoo/.git/
(INFO) [10:22:16] git_aggregator.repo  odoo   Switch to branch 13.0
Switched to a new branch '13.0'
(INFO) [10:22:16] git_aggregator.repo  odoo   Adding remote ocb <https://github.com/OCA/OCB.git>
(INFO) [10:22:16] git_aggregator.repo  odoo   Adding remote odoo <https://github.com/odoo/odoo.git>
(INFO) [10:22:16] git_aggregator.repo  odoo   Adding remote openupgrade <https://github.com/OCA/OpenUpgrade.git>
(INFO) [10:22:16] git_aggregator.repo  odoo   Fetching required remotes
From https://github.com/OCA/OCB
 * branch              13.0       -> FETCH_HEAD
 * [new branch]        13.0       -> ocb/13.0
(INFO) [10:23:04] git_aggregator.repo  odoo   Pull ocb, 13.0
Checking out files: 100% (25504/25504), done.
(INFO) [10:23:12] git_aggregator.repo  odoo   Execute shell after commands
(INFO) [10:23:12] git_aggregator.repo  odoo   End aggregation of /opt/odoo/custom/src/odoo
```
then ``invoke start``
returns
```
Reinitialized existing Git repository in /home/int/subproject/.git/
pre-commit installed at .git/hooks/pre-commit
The SMTP_REAL_NON_CANONICAL_DEFAULT variable is not set. Defaulting to a blank string.
Creating network "subproject_default" with the default driver
Creating volume "subproject_filestore" with default driver
Creating volume "subproject_db" with default driver
Creating subproject_smtp_1                   ... done
Creating subproject_wdb_1                    ... done
Creating subproject_gravatar_proxy_1         ... done
Creating subproject_cdnjs_cloudflare_proxy_1 ... done
Creating subproject_fonts_googleapis_proxy_1 ... done
Creating subproject_fonts_gstatic_proxy_1    ... done
Creating subproject_google_proxy_1           ... done
Creating subproject_db_1                     ... done
Creating subproject_odoo_1                   ... done
Creating subproject_odoo_proxy_1             ... done
```
then ``docker-compose logs``
<details> 
<summary>returns</summary>

```
Attaching to subproject_odoo_proxy_1, subproject_odoo_1, subproject_google_proxy_1, subproject_fonts_gstatic_proxy_1, subproject_db_1, subproject_fonts_googleapis_proxy_1, subproject_gravatar_proxy_1, subproject_cdnjs_cloudflare_proxy_1, subproject_wdb_1, subproject_smtp_1
cdnjs_cloudflare_proxy_1  | INFO:root:Resolved cdnjs.cloudflare.com to 104.16.132.229
cdnjs_cloudflare_proxy_1  | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr tcp-connect:104.16.132.229:80
cdnjs_cloudflare_proxy_1  | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr tcp-connect:104.16.132.229:443
db_1                      | The files belonging to this database system will be owned by user "postgres".
db_1                      | This user must also own the server process.
db_1                      | 
db_1                      | The database cluster will be initialized with locale "en_US.utf8".
db_1                      | The default database encoding has accordingly been set to "UTF8".
db_1                      | The default text search configuration will be set to "english".
db_1                      | 
db_1                      | Data page checksums are disabled.
db_1                      | 
db_1                      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1                      | creating subdirectories ... ok
db_1                      | selecting dynamic shared memory implementation ... posix
db_1                      | selecting default max_connections ... 100
db_1                      | selecting default shared_buffers ... 128MB
db_1                      | selecting default time zone ... UTC
db_1                      | creating configuration files ... ok
db_1                      | running bootstrap script ... ok
db_1                      | sh: locale: not found
db_1                      | 2020-06-09 10:24:16.943 UTC [29] WARNING:  no usable system locales were found
db_1                      | performing post-bootstrap initialization ... ok
db_1                      | syncing data to disk ... ok
db_1                      | 
db_1                      | initdb: warning: enabling "trust" authentication for local connections
db_1                      | You can change this by editing pg_hba.conf or using the option -A, or
db_1                      | --auth-local and --auth-host, the next time you run initdb.
db_1                      | 
db_1                      | Success. You can now start the database server using:
db_1                      | 
db_1                      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1                      | 
db_1                      | waiting for server to start....2020-06-09 10:24:17.809 GMT [34] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
db_1                      | 2020-06-09 10:24:17.811 GMT [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                      | 2020-06-09 10:24:17.828 GMT [35] LOG:  database system was shut down at 2020-06-09 10:24:17 GMT
db_1                      | 2020-06-09 10:24:17.832 GMT [34] LOG:  database system is ready to accept connections
db_1                      |  done
db_1                      | server started
db_1                      | CREATE DATABASE
db_1                      | 
db_1                      | 
db_1                      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1                      | 
db_1                      | 2020-06-09 10:24:18.054 GMT [34] LOG:  received fast shutdown request
db_1                      | waiting for server to shut down....2020-06-09 10:24:18.056 GMT [34] LOG:  aborting any active transactions
db_1                      | 2020-06-09 10:24:18.058 GMT [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
db_1                      | 2020-06-09 10:24:18.058 GMT [36] LOG:  shutting down
db_1                      | 2020-06-09 10:24:18.071 GMT [34] LOG:  database system is shut down
db_1                      |  done
db_1                      | server stopped
db_1                      | 
db_1                      | PostgreSQL init process complete; ready for start up.
db_1                      | 
db_1                      | 2020-06-09 10:24:18.167 GMT [1] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
db_1                      | 2020-06-09 10:24:18.167 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                      | 2020-06-09 10:24:18.167 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1                      | 2020-06-09 10:24:18.171 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                      | 2020-06-09 10:24:18.189 GMT [45] LOG:  database system was shut down at 2020-06-09 10:24:18 GMT
db_1                      | 2020-06-09 10:24:18.193 GMT [1] LOG:  database system is ready to accept connections
db_1                      | 2020-06-09 10:25:26.780 GMT [55] ERROR:  relation "ir_module_module" does not exist at character 28
fonts_googleapis_proxy_1  | INFO:root:Resolved fonts.googleapis.com to 172.217.20.106
fonts_googleapis_proxy_1  | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr tcp-connect:172.217.20.106:80
fonts_googleapis_proxy_1  | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr tcp-connect:172.217.20.106:443
fonts_gstatic_proxy_1     | INFO:root:Resolved fonts.gstatic.com to 172.217.17.35
fonts_gstatic_proxy_1     | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr tcp-connect:172.217.17.35:80
fonts_gstatic_proxy_1     | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr tcp-connect:172.217.17.35:443
db_1                      | 2020-06-09 10:25:26.780 GMT [55] STATEMENT:  SELECT latest_version FROM ir_module_module WHERE name='base'
db_1                      | 2020-06-09 10:25:27.788 GMT [55] ERROR:  relation "ir_module_module" does not exist at character 28
db_1                      | 2020-06-09 10:25:27.788 GMT [55] STATEMENT:  SELECT latest_version FROM ir_module_module WHERE name='base'
google_proxy_1            | INFO:root:Resolved www.google.com to 172.217.19.196
google_proxy_1            | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr tcp-connect:172.217.19.196:80
google_proxy_1            | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr tcp-connect:172.217.19.196:443
gravatar_proxy_1          | INFO:root:Resolved www.gravatar.com to 192.0.73.2
gravatar_proxy_1          | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr tcp-connect:192.0.73.2:80
gravatar_proxy_1          | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr tcp-connect:192.0.73.2:443
odoo_1                    | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1                    |   """)
odoo_1                    | doodba INFO: Waiting until postgres is listening at db...
odoo_1                    | doodba INFO: Unaccent extension installed
odoo_proxy_1              | INFO:root:Executing: socat tcp-listen:6899,fork,reuseaddr tcp-connect:odoo:6899
odoo_proxy_1              | INFO:root:Executing: socat tcp-listen:8069,fork,reuseaddr tcp-connect:odoo:8069
smtp_1                    | 2020/06/09 10:24:10 Using in-memory storage
smtp_1                    | 2020/06/09 10:24:10 [SMTP] Binding to address: 0.0.0.0:1025
smtp_1                    | 2020/06/09 10:24:10 Serving under http://0.0.0.0:8025/
smtp_1                    | [HTTP] Binding to address: 0.0.0.0:8025
smtp_1                    | Creating API v1 with WebPath: 
smtp_1                    | Creating API v2 with WebPath: 
smtp_1                    | [APIv1] KEEPALIVE /api/v1/events
odoo_1                    | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1                    | doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
odoo_1                    | doodba INFO: Executing odoo --limit-memory-soft=0 --limit-time-real-cron=9999999 --limit-time-real=9999999 --workers=0 --dev=reload,qweb,werkzeug,xml
odoo_1                    | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1                    |   """)
odoo_1                    | /usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
odoo_1                    |   RequestsDependencyWarning)
odoo_1                    | 2020-06-09 10:24:23,300 1 INFO ? odoo: Odoo version 13.0 
odoo_1                    | 2020-06-09 10:24:23,301 1 INFO ? odoo: Using configuration file at /opt/odoo/auto/odoo.conf 
odoo_1                    | 2020-06-09 10:24:23,301 1 INFO ? odoo: addons paths: ['/opt/odoo/custom/src/odoo/odoo/addons', '/var/lib/odoo/addons/13.0', '/opt/odoo/auto/addons'] 
odoo_1                    | 2020-06-09 10:24:23,303 1 INFO ? odoo: database: odoo@db:5432 
odoo_1                    | 2020-06-09 10:24:24,279 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
odoo_1                    | 2020-06-09 10:24:24,968 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/custom/src/odoo/odoo/addons 
odoo_1                    | 2020-06-09 10:24:24,969 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/13.0 
odoo_1                    | 2020-06-09 10:24:24,969 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/auto/addons 
odoo_1                    | 2020-06-09 10:24:26,696 1 INFO ? odoo.service.server: AutoReload watcher running with inotify 
odoo_1                    | 2020-06-09 10:24:26,704 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 37969ca152e6:8069 
odoo_1                    | 2020-06-09 10:24:26,715 1 ERROR ? odoo.modules.loading: Database devel not initialized, you can force it with `-i base` 
odoo_1                    | 2020-06-09 10:25:26,781 1 ERROR devel odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
odoo_1                    | ERROR: relation "ir_module_module" does not exist
odoo_1                    | LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
odoo_1                    |                                    ^
odoo_1                    |  
odoo_1                    | 2020-06-09 10:25:26,784 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database devel. 
odoo_1                    | 2020-06-09 10:25:27,788 1 ERROR devel odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
odoo_1                    | ERROR: relation "ir_module_module" does not exist
odoo_1                    | LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
odoo_1                    |                                    ^
odoo_1                    |  
odoo_1                    | 2020-06-09 10:25:27,789 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database devel. 
```
</details>

**Comment by Yajo** [comment]
Well, it's working AFAICS.

It's just telling you you didn't initialize the database, which you can do using https://github.com/Tecnativa/doodba-copier-template/issues/27#issuecomment-610273675, but is not "our" problem but odoo's.

Make sure to follow the steps closely next time, regards! :wink:

**Comment by bosd** [comment]
Many thanks!
Initialized the database in the devel environment succesfully! ;-)
However, I was unable to acces is by navigating to
<ipadress vps>:13069

I have the globalwhitelist running..


So, I tried firing up the test environment with.
`docker-compose -f test.yaml up`

That throws the 
```
db_1    | 2020-06-09 12:16:53.161 GMT [32] FATAL:  password authentication failed for user "odoo"
db_1    | 2020-06-09 12:16:53.161 GMT [32] DETAIL:  Password does not match for user "odoo".

```
as mentioned in  #Tecnativa/doodba#315 and in #27 (comment)
So I run the command also for the test environment.
``docker-compose run --rm odoo --stop-after-init -i base``
However for the test environment it does not solve the issue.

**Comment by Yajo** [comment]
> I was unable to acces is by navigating to
> http://ipadressvps:13069

Great! You shouldn't be.

You'll find odoo in http://localhost:13069 instead.



> So, I tried firing up the test environment with.
> `docker-compose -f test.yaml up`
> 
> That throws the
> 
> ```
> db_1    | 2020-06-09 12:16:53.161 GMT [32] FATAL:  password authentication failed for user "odoo"
> db_1    | 2020-06-09 12:16:53.161 GMT [32] DETAIL:  Password does not match for user "odoo".
> ```

Of course. You cannot be switching environments just because. Databases differ, passwords differ... You don't want your devs to know your staging secrets.

Different environments are initialized separately, that's by design, so of course you devel DB will fail in test, and viceversa.

You need to know your tools better, but that means reading many docs: https://github.com/Tecnativa/doodba-copier-template/blob/master/docs/daily-usage.md#prior-knowledge

It's worth it though :wink:

**Comment by bosd** [comment]
ok, I went trough the docs already.
But clearly I am missing something here.
I've learned a lot form your youtube video, but that is using the old scaffolding model.
Some of those things I was able to do under the old scaffolding model, were'nt maybe not the best practice. But I managed my way around. :)

I installed it on a headless vps. so http://localhost:13069 is not going to work for me.
I've made an entry in my hosts file to point ipadressvps to test.subproject.com

ok, you made it clear I need to initialize the test evironment.
yet, I have no clue how to do so..

**Comment by Yajo** [comment]
> I installed it on a headless vps. so http://localhost:13069 is not going to work for me.

This doesn't support that use case out of the box. You'll have to patch manually your `devel.yaml` to let it listen on other interfaces than `127.0.0.1`.

Here are the docs: https://docs.docker.com/compose/compose-file/compose-file-v2/#ports

**Comment by pleirb** [comment]
> 

The exact same thing happens to me as you, only I'm trying to make it work in production mode. Have you managed to solve?

**Comment by pleirb** [comment]
Finally, to solve, what they comment here has helped me: https://github.com/Tecnativa/doodba/issues/418
