### ISSUE TITLE
Invoke error on template building

### ISSUE THREAD

**Issue by sotolucas** [Tecnativa/doodba-copier-template#62]
Hi there @Yajo .
First of all, I want to thank Tecnativa for this awesome job.

I'm using:

- Ubuntu 18.04 Bionic Beaver (clean install)
- git 2.27.0
- invoke 0.11.1
-  copier 3.2.0
- pre-commit 2.5.1

After installing all required packages, `run copier copy gh:...` and answer all required questions I get the following error.
I couldn't dig deeper as I'm new to this tools:
```
 > Running task 1 of 1: invoke develop
'develop' did not receive all required positional arguments!
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/home/lsoto/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/lsoto/.local/lib/python3.6/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/lsoto/.local/lib/python3.6/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/cli.py", line 17, in _wrapper
    return method(*args, **kwargs)
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/cli.py", line 158, in main
    self.parent._copy(template_src, destination_path)
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/cli.py", line 121, in _copy
    **kwargs,
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/main.py", line 142, in copy
    copy_local(conf=conf)
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/main.py", line 196, in copy_local
    conf, render, [{"task": t, "extra_env": {"STAGE": "task"}} for t in conf.tasks]
  File "/home/lsoto/.local/lib/python3.6/site-packages/copier/main.py", line 369, in run_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'invoke develop' returned non-zero exit status 1.
```

Any hint?
Thank you in advance.
P.D.: I couldn't install required packages with pipx as it seems there are some dependencies incompatibilities with virtualenv, so I went straight with pip.

**Comment by Yajo** [comment]
Your invoke is too old, please install with pipx.
